# Generated by Django 3.2.5 on 2021-07-23 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="link",
            name="image",
            field=models.ImageField(null=True, upload_to="", verbose_name="icon"),
        ),
        migrations.AddField(
            model_name="link",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="auth.user",
            ),
            preserve_default=False,
        ),
    ]
