# Generated by Django 3.2.5 on 2021-07-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_auto_20210726_2315"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(null=True, upload_to="", verbose_name="icon"),
        ),
    ]
