# Generated by Django 3.2.5 on 2021-07-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0005_auto_20210727_0027"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="url",
            new_name="link",
        ),
    ]
