# Generated by Django 3.2.5 on 2021-07-27 17:40

from django.db import migrations, models
import django.db.models.deletion

from ...links.models import ProfileTheme


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0007_auto_20210727_2248"),
    ]

    operations = []
