# Generated by Django 3.2.5 on 2021-07-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0008_auto_20210727_2310"),
    ]

    operations = []
