# Generated by Django 3.2.5 on 2021-07-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0009_profiletheme"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("light", "light"),
                            ("dark", "dark"),
                            ("cupcake", "cupcake"),
                            ("bumblebee", "bumblebee"),
                            ("emerald", "emerald"),
                            ("corporate", "corporate"),
                            ("synthwave", "synthwave"),
                            ("retro", "retro"),
                            ("cyberpunk", "cyberpunk"),
                            ("valentine", "valentine"),
                            ("halloween", "halloween"),
                            ("garden", "garden"),
                            ("forest", "forest"),
                            ("aqua", "aqua"),
                            ("lofi", "lofi"),
                            ("pastel", "pastel"),
                            ("fantasy", "fantasy"),
                            ("wireframe", "wireframe"),
                            ("black", "black"),
                            ("luxury", "luxury"),
                            ("dracula", "dracula"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
