# Generated by Django 3.2.5 on 2021-07-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0010_profiletheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="theme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="links.profiletheme",
            ),
        ),
    ]
