# Generated by Django 3.2.5 on 2021-07-30 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0012_auto_20210728_1425"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("0b5c71bf-d9f0-4f71-9f3f-d42eb54d6cf3"),
                primary_key=True,
                serialize=False,
                verbose_name="UUID",
            ),
        ),
    ]
