# Generated by Django 3.2.5 on 2021-08-01 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0015_auto_20210731_0408"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="link",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("c6b51556-d8fa-4dd0-88ae-5f5e585e01ca"),
                verbose_name="UUID",
            ),
        ),
    ]
