# Generated by Django 3.2.5 on 2021-08-01 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0016_auto_20210801_2207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, verbose_name="UUID"
            ),
        ),
    ]
