# Generated by Django 3.2.5 on 2021-08-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0018_alter_profiletheme_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
